const { userBlockageTimeForTooManySignUpRequests } = require('../configuration');
module.exports = {
    userNotExist: 'User doesn\'t exist',
    userAlreadyExist: 'User already exist',
    invalidService: 'Invalid service request. Please check validity',
    invalid: 'Invalid orders request. Please check validity',
    invalidCart: 'Invalid cart. Please check validity',
    invalidParameter: 'Invalid parameter request. Please check validity',
    invalidCollectionType: 'Invalid collection request. Please check validity',
    invalidPaymentType: 'Invalid payment type. Please check validity',
    invalidStatusChange: 'Invalid status change. Please check again',
    courierInformationRequired: 'Courier Information required',
    noCourierInOrder: 'Courier is not collection type in order',
    noPickupInOrder: 'Pickup is not collection type in order',
    noCollectionType: 'No Collection type',
    allOrdersNotReady: 'All orders not ready',
    noOrdersInCart: 'No orders in cart',
    permissionDenied: 'Permission Denied',
    accountAlreadyExists: 'Account Already Exists',
    invalidToken: 'Invalid Token',
    sessionExpired: 'Session Expired',
    invalidDaiictUser: 'Invalid DA-IICT user',
    userDeactivated: 'User is deactivated',
    inactiveCollectionType: 'Requested collection type is currently inactive',
    notFoundCollectionType: 'Requested collection type doesn\'t exist',
    notBelongToCollectionTypeCategory: 'Requested category and collection type doesn\'t match',
    collectionTypeNotInUnion: 'Requested collection type is not allowed for all service',
    paymentInProcessing: 'Payment already in process',
    paymentFailed: 'Payment Failed',
    blockUser: `Too many request you are blocked for ${userBlockageTimeForTooManySignUpRequests} hours`,
    signUpRequestExpired: 'Your verification link has expired. Sign up again',
};
