module.exports = {
    User:{
        superAdmin:{
            canUpdate:[
                "name" , 
                "secondaryEmail", 
                "contactNo", 
                "gender", 
                "programme", 
                "requestedServices",
                "password", 
            ],
            canRead:[
                "name" , 
                "secondaryEmail", 
                "contactNo", 
                "gender", 
                "programme", 
                "userType", 
                "isActive", 
                "requestedServices", 
                "notifications", 
                "daiictId", 
                "primaryEmail", 
                "createdOn", 
            ],
            canCreate:[
                "name" , 
                "secondaryEmail", 
                "contactNo", 
                "gender", 
                "programme", 
                "requestedServices", 
                "daiictId", 
                "primaryEmail", 
                "password", 
            ],
        },
        student:{
            canUpdate:[
                "name" , 
                "secondaryEmail", 
                "contactNo", 
                "gender", 
                "programme", 
                "requestedServices",   
                "password", 
            ],
            canRead:[
                "name" , 
                "secondaryEmail", 
                "contactNo", 
                "gender", 
                "programme", 
                "userType", 
                "isActive", 
                "requestedServices", 
                "notifications", 
                "daiictId", 
                "primaryEmail", 
                "createdOn", 
            ],
            canCreate:[
                "name" , 
                "secondaryEmail", 
                "contactNo", 
                "gender", 
                "programme", 
                "requestedServices", 
                "daiictId", 
                "primaryEmail", 
                "password", 
            ],
        },
    },
    News:{
        superAdmin:{
            canRead:[
                "_id",
                "message",
                "createdOn",
            ],
            canCreate:[
                "message",
            ],
            canUpdate:[
                "message",
            ],
        },
        student:{
            canRead:[
                "message",
                "createdOn",
            ],
            canCreate:[
                
            ],
            canUpdate:[
                
            ],
        },
    },
    Notification:{
        superAdmin:{
            canRead:[
                "_id",
                "message",
                "createdOn",
            ],
            canCreate:[
                "message",
            ],
            canUpdate:[
                "message",
            ],
        },
        student:{
            canRead:[
                "message",
                "createdOn",
            ],
            canCreate:[
                
            ],
            canUpdate:[
                
            ],
        },
    },
    Order:{
        superAdmin:{
            canRead:[
            ],
            canCreate:[
            ],
            canUpdate:[
            ],
        },
        student:{
            canRead:[
    
            ],
            canCreate:[
    
            ],
            canUpdate:[
                
            ]
        },
    },
    Service:{
        superAdmin:{
            canRead:[
                '_id',
                'name',
                'description',
                'createdOn',
                'createdBy',
                'isApplicationSpecific',
                'isAvailableForAlumni',
                'isCourierAvailable',
                'isSpecialService',
                'isActive',
                'maxUnits',
                'baseCharge',
                'availableParameters',
            ],
            canCreate:[
                'name',
                'description',
                'isApplicationSpecific',
                'isAvailableForAlumni',
                'isCourierAvailable',
                'isSpecialService',
                'isActive',
                'maxUnits',
                'baseCharge',
                'availableParameters',
            ],
            canUpdate:[
                'name',
                'description',
                'isApplicationSpecific',
                'isAvailableForAlumni',
                'isCourierAvailable',
                'isSpecialService',
                'isActive',
                'maxUnits',
                'baseCharge',
                'availableParameters',
            ],
        },
        student:{
            canRead:[
                '_id',
                'name',
                'description',
                'maxUnits',
                'baseCharge',
                'availableParameters',
            ],
            canCreate:[
    
            ],
            canUpdate:[
                
            ]
        },
    },
    Collector:{
        superAdmin:{
            canRead:[
            ],
            canCreate:[
            ],
            canUpdate:[
            ],
        },
        student:{
            canRead:[
    
            ],
            canCreate:[
    
            ],
            canUpdate:[
                
            ]
        },
    },
    Parameter:{
        superAdmin:{
            canRead:[
                "_id",
                "name",
                "description",
                "baseCharge",
                "createdOn",
                "createdBy"
            ],
            canCreate:[
                "_id",
                "name",
                "description",
                "baseCharge",
            ],
            canUpdate:[
                "name",
                "description",
                "baseCharge",
            ],
        },
        student:{
            canRead:[
                "_id",
                "name",
                "description",
                "baseCharge",
            ],
            canCreate:[
    
            ],
            canUpdate:[
                
            ]
        },
    },
    AccessLevel:{
        superAdmin:{
            canRead:[
            ],
            canCreate:[
            ],
            canUpdate:[
            ],
        },
        student:{
            canRead:[
    
            ],
            canCreate:[
    
            ],
            canUpdate:[
                
            ]
        },
    },
    Role:{
        superAdmin:{
            canRead:[
            ],
            canCreate:[
            ],
            canUpdate:[
            ],
        },
        student:{
            canRead:[
    
            ],
            canCreate:[
    
            ],
            canUpdate:[
                
            ]
        },
    },
}